services:
  redis:
    image: redis:7
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a '${REDIS_PASSWORD}' ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data: